### PR TITLE
Multiple themes + path relative

### LINKED ISSUE #5: Allow themes to be in another folder
My `core-theme` is loaded using Composer and is therefore in a vendor folder. This core theme is again extended in a local theme in the `themes` folder, which is called `base-theme`.

For the `core-theme` I cannot do a diff:

```
bin/console webgriffe:upgrade:template-changes v1.7.11 v1.8.12 --theme=core-theme --legacy
ERROR: Cannot search "/var/www/html/symfony/themes/core-theme/" cause it does not exists.
```

The `base-theme` does work. 

Later I figured out this works, but I'm not sure this is intended to be working:

```
bin/console webgriffe:upgrade:template-changes v1.7.11 v1.8.12 --theme=../vendor/project/core-theme --legacy
```

### PR DESCRIPTION
**Pull request by LucaGallinari**
Fixes #5 

- [x] Can specify multiple values for theme option
- [x] Theme path must start from the kernel.project_dir

### CODE REVIEW

**Review by mmenozzi — APPROVED** [review]

File: src/Command/TemplateChangesCommand.php [hunk 1]
```diff
@@ -193,7 +201,7 @@ static function (string $file) use ($targetDir): string {
 
     private function computeThemeTemplateFilesChangedAndOverridden(array $versionChangedFiles, string $themeName, bool $legacyMode): void
     {
-        $targetDir = $this->rootPath . 'themes' . \DIRECTORY_SEPARATOR . $themeName . \DIRECTORY_SEPARATOR;
+        $targetDir = $this->rootPath . $themeName . \DIRECTORY_SEPARATOR;
```
Comment (lruozzi9) [inline src/Command/TemplateChangesCommand.php:204]: I think we should check here if $themeName end with a / or not bifore concatenating it. Pheraps we could also remove at all the directory separator?

Comment (mmenozzi) [reply src/Command/TemplateChangesCommand.php:204]: An elegant way to do it is with

rtrim($themeName, \DIRECTORY_SEPARATOR) . \DIRECTORY_SEPARATOR

Comment (LucaGallinari) [reply src/Command/TemplateChangesCommand.php:204]: Yes, absolutely
